---
- name: Create "{{ samba_guest_account }}" group
  ansible.builtin.group:
    name: "{{ samba_guest_account }}"
    state: present

- name: Create "{{ samba_guest_account }}" user
  ansible.builtin.user:
    name: "{{ samba_guest_account }}"
    state: present
    system: yes
    update_password: on_create
    create_home: no
    group: "{{ samba_guest_account }}"
    shell: /usr/sbin/nologin

- ansible.builtin.include_role:
    name: bertvv.samba
