---
- name: Set login banner
  ansible.builtin.copy:
    src: motd.txt
    dest: /etc/motd

- name: Upgrade all packages
  ansible.builtin.apt:
    upgrade: yes
    state: latest
  become: true
  when: keep_packages_updated
  tags:
    - skip_ansible_lint

- name: Install some packages
  ansible.builtin.apt:
    name: "{{ ansible_nas_extra_packages }}"
    state: present
  register: result
  until: result is succeeded

- name: "Set hostname to {{ ansible_nas_hostname }}"
  ansible.builtin.hostname:
    name: "{{ ansible_nas_hostname }}"
  become: true

- name: "Set timezone to {{ ansible_nas_timezone }}"
  community.general.timezone:
    name: "{{ ansible_nas_timezone }}"
