---
- name: Install necessary packages for docker
  ansible.builtin.apt:
    name:
      - python3-pip
      - python3-setuptools
      - python3-docker
    state: present
  register: result
  until: result is succeeded
  become: true

- name: Create Docker home directory
  ansible.builtin.file:
    path: "{{ docker_home }}"
    mode: 0755
    state: directory
  become: true

- ansible.builtin.include_role:
    name: geerlingguy.docker
    apply:
      become: true
  vars:
    docker_packages_state: latest
    docker_users:
      - "{{ ansible_nas_user }}"
    docker_daemon_options:
      data-root: "{{ docker_image_directory }}"
      storage-driver: "{{ docker_storage_driver }}"
