entryPoints:
  web:
    address: ":{{ traefik_port_http }}"
    http:
      redirections:
        entryPoint:
          to: "websecure"
          scheme: "https"

  websecure:
    address: ":{{ traefik_port_https }}"
    asDefault: true
    http:
      tls:
        certResolver: "letsencrypt"

providers:
  providersThrottleDuration: "2s"
  docker:
    exposedByDefault: false
  file:
    directory: "/etc/traefik/providers"
    watch: true

api:
  dashboard: false
  insecure: false

log:
  level: "{{ traefik_log_level }}"

ping:
  terminatingStatusCode: 0

certificatesResolvers:
  letsencrypt:
    acme:
      email: "{{ ansible_nas_email }}"
      storage: "/letsencrypt/acme.json"
      caServer: "{{ traefik_acme_server }}"

      dnsChallenge:
        provider: "{{ traefik_dns_provider }}"

metrics:
  prometheus: {}

serversTransport:
  insecureSkipVerify: true

accessLog: false