---
- name: Permission Data
  hosts: all
  tasks:
    - name: Warning!
      ansible.builtin.debug:
        msg: This playbook will repermission ALL existing data in the shares defined in group_vars/all.yml to be owned by the "{{ samba_guest_account }}" user and group. If this is not what you want, exit now.

    - name: 20s to change your mind...
      ansible.builtin.pause:
        seconds: 20

    - name: "Permission share data"
      ansible.builtin.file:
        path: "{{ item.path }}"
        owner: "{{ samba_guest_account }}"
        group: "{{ samba_guest_account }}"
        mode: "u=rwX,g=rwX,o=rX"
        recurse: true
      loop: "{{ samba_shares }}"
